CREATE (r1:Role {id: 'role-ux-researcher', name: 'UX Researcher', type: 'current', description: 'Conducts user research to inform product design decisions'});
CREATE (r2:Role {id: 'role-ux-designer', name: 'UX Designer', type: 'current', description: 'Designs user interfaces and experiences for digital products'});
CREATE (r3:Role {id: 'role-visual-designer', name: 'Visual Designer', type: 'current', description: 'Creates visual elements including layout, color, and typography'});
CREATE (r4:Role {id: 'role-content-designer', name: 'Content Designer', type: 'current', description: 'Creates and manages content for digital products'});
CREATE (r5:Role {id: 'role-ia', name: 'Information Architect', type: 'current', description: 'Organizes and structures information in digital products'});
CREATE (r6:Role {id: 'role-product-designer', name: 'Product Designer', type: 'current', description: 'End-to-end product design from research to visual design'});
CREATE (r7:Role {id: 'role-graphic-designer', name: 'Graphic Designer', type: 'current', description: 'Creates visual content for print and digital media'});
CREATE (r8:Role {id: 'role-ai-design-researcher', name: 'AI Design Researcher', type: 'target', description: 'Combines UX research with AI evaluation and AI-powered research methodologies'});
CREATE (r9:Role {id: 'role-ai-ux-lead', name: 'AI UX Lead', type: 'target', description: 'Leads UX teams in designing AI-powered products and integrating AI into design processes'});
CREATE (r10:Role {id: 'role-conv-ui-designer', name: 'Conversational UI Designer', type: 'target', description: 'Designs conversational interfaces for AI chatbots and voice assistants'});
CREATE (r11:Role {id: 'role-ai-content-strategist', name: 'AI Content Strategist', type: 'target', description: 'Develops content strategies that leverage AI for creation, personalization, and optimization'});
CREATE (r12:Role {id: 'role-ai-product-designer', name: 'AI Product Designer', type: 'target', description: 'Designs AI-native products with deep understanding of AI capabilities and limitations'});
CREATE (r13:Role {id: 'role-ai-design-lead', name: 'AI Design Lead', type: 'target', description: 'Strategic design leadership role bridging design teams with AI capabilities'});
CREATE (r14:Role {id: 'role-ai-design-engineer', name: 'AI Design Engineer', type: 'target', description: 'Bridges design and engineering in AI product development'});
CREATE (r15:Role {id: 'role-ai-ethics-designer', name: 'AI Ethics Designer', type: 'target', description: 'Specializes in designing ethical, fair, and transparent AI experiences'});
CREATE (t1:Tool {id: 'tool-figma-ai', name: 'Figma AI', category: 'Design', url: 'https://figma.com'});
CREATE (t2:Tool {id: 'tool-midjourney', name: 'Midjourney', category: 'Image Generation', url: 'https://midjourney.com'});
CREATE (t3:Tool {id: 'tool-dalle', name: 'DALL-E', category: 'Image Generation', url: 'https://openai.com/dall-e'});
CREATE (t4:Tool {id: 'tool-chatgpt', name: 'ChatGPT', category: 'LLM', url: 'https://chat.openai.com'});
CREATE (t5:Tool {id: 'tool-claude', name: 'Claude', category: 'LLM', url: 'https://claude.ai'});
CREATE (t6:Tool {id: 'tool-adobe-firefly', name: 'Adobe Firefly', category: 'Image Generation', url: 'https://firefly.adobe.com'});
CREATE (t7:Tool {id: 'tool-usertesting-ai', name: 'UserTesting AI', category: 'Research', url: 'https://usertesting.com'});
CREATE (t8:Tool {id: 'tool-maze-ai', name: 'Maze AI', category: 'Research', url: 'https://maze.co'});
CREATE (t9:Tool {id: 'tool-stable-diffusion', name: 'Stable Diffusion', category: 'Image Generation', url: 'https://stability.ai'});
CREATE (t10:Tool {id: 'tool-copilot', name: 'GitHub Copilot', category: 'Code', url: 'https://github.com/features/copilot'});
CREATE (t11:Tool {id: 'tool-v0', name: 'v0 by Vercel', category: 'Code', url: 'https://v0.dev'});
CREATE (t12:Tool {id: 'tool-cursor', name: 'Cursor', category: 'Code', url: 'https://cursor.sh'});
CREATE (t13:Tool {id: 'tool-framer-ai', name: 'Framer AI', category: 'Design', url: 'https://framer.com'});
CREATE (t14:Tool {id: 'tool-relume', name: 'Relume', category: 'Design', url: 'https://relume.io'});
CREATE (t15:Tool {id: 'tool-galileo-ai', name: 'Galileo AI', category: 'Design', url: 'https://galileo.ai'});
CREATE (c1:Course {id: 'course-ixdf-ai-design', name: 'AI for Designers (IxDF)', provider: 'Interaction Design Foundation', url: 'https://www.interaction-design.org/', duration_weeks: 4, cost: 'Subscription', level: 'Beginner'});
CREATE (c2:Course {id: 'course-coursera-prompt', name: 'Prompt Engineering for Creatives', provider: 'Coursera', url: 'https://coursera.org/', duration_weeks: 3, cost: '$49', level: 'Beginner'});
CREATE (c3:Course {id: 'course-nngroup-ai-ux', name: 'AI and UX: Design Guidelines', provider: 'NNGroup', url: 'https://www.nngroup.com/', duration_weeks: 1, cost: '$399', level: 'Intermediate'});
CREATE (c4:Course {id: 'course-figma-ai-workshop', name: 'Figma AI Workshop', provider: 'Figma', url: 'https://figma.com/', duration_weeks: 1, cost: 'Free', level: 'Beginner'});
CREATE (c5:Course {id: 'course-ml-nontech', name: 'Machine Learning for Non-Technical People', provider: 'IxDF', url: 'https://www.interaction-design.org/', duration_weeks: 3, cost: 'Subscription', level: 'Beginner'});
CREATE (c6:Course {id: 'course-ai-ethics', name: 'AI Ethics for Design Professionals', provider: 'Coursera', url: 'https://coursera.org/', duration_weeks: 2, cost: '$49', level: 'Intermediate'});
CREATE (c7:Course {id: 'course-conv-design', name: 'Conversational Design Masterclass', provider: 'Google', url: 'https://developers.google.com/actions/design', duration_weeks: 4, cost: 'Free', level: 'Intermediate'});
CREATE (c8:Course {id: 'course-midjourney-mastery', name: 'Midjourney Mastery for Designers', provider: 'Udemy', url: 'https://udemy.com/', duration_weeks: 2, cost: '$29', level: 'Beginner'});
CREATE (c9:Course {id: 'course-ai-research-methods', name: 'AI-Powered Research Methods', provider: 'NNGroup', url: 'https://www.nngroup.com/', duration_weeks: 2, cost: '$399', level: 'Intermediate'});
CREATE (c10:Course {id: 'course-design-systems-ai', name: 'Design Systems in the Age of AI', provider: 'Smashing Magazine', url: 'https://smashingmagazine.com/', duration_weeks: 1, cost: '$99', level: 'Intermediate'});
CREATE (c11:Course {id: 'course-data-viz-ai', name: 'AI-Powered Data Visualization', provider: 'Coursera', url: 'https://coursera.org/', duration_weeks: 3, cost: '$49', level: 'Intermediate'});
CREATE (c12:Course {id: 'course-genui-basics', name: 'Generative UI: From Concept to Code', provider: 'Udemy', url: 'https://udemy.com/', duration_weeks: 3, cost: '$39', level: 'Intermediate'});
CREATE (c13:Course {id: 'course-voice-ai-design', name: 'Designing for Voice AI', provider: 'IxDF', url: 'https://www.interaction-design.org/', duration_weeks: 3, cost: 'Subscription', level: 'Intermediate'});
CREATE (c14:Course {id: 'course-ai-content-strategy', name: 'AI Content Strategy', provider: 'Content Design Academy', url: 'https://contentdesign.london/', duration_weeks: 4, cost: '$199', level: 'Intermediate'});
CREATE (c15:Course {id: 'course-rag-basics', name: 'RAG Systems for Product People', provider: 'Coursera', url: 'https://coursera.org/', duration_weeks: 2, cost: '$49', level: 'Advanced'});
CREATE (c16:Course {id: 'course-human-ai-collab', name: 'Human-AI Collaboration Patterns', provider: 'IxDF', url: 'https://www.interaction-design.org/', duration_weeks: 3, cost: 'Subscription', level: 'Intermediate'});
CREATE (c17:Course {id: 'course-ai-persona-design', name: 'Designing AI Personas & Agents', provider: 'Udemy', url: 'https://udemy.com/', duration_weeks: 2, cost: '$34', level: 'Intermediate'});
CREATE (c18:Course {id: 'course-multimodal-ai', name: 'Multimodal AI for Creative Professionals', provider: 'Coursera', url: 'https://coursera.org/', duration_weeks: 4, cost: '$49', level: 'Advanced'});
CREATE (c19:Course {id: 'course-ai-accessibility', name: 'AI-Powered Accessibility Auditing', provider: 'Deque University', url: 'https://dequeuniversity.com/', duration_weeks: 2, cost: '$100', level: 'Intermediate'});
CREATE (c20:Course {id: 'course-prompt-chaining', name: 'Advanced Prompt Chaining for Designers', provider: 'Udemy', url: 'https://udemy.com/', duration_weeks: 2, cost: '$39', level: 'Intermediate'});
