MATCH (r:Role {id: 'role-ux-researcher'}), (s:DesignSkill {id: 'ds-qual-analysis'}) CREATE (r)-[:REQUIRES {importance: 'core'}]->(s);
MATCH (r:Role {id: 'role-ux-researcher'}), (s:DesignSkill {id: 'ds-user-interviews'}) CREATE (r)-[:REQUIRES {importance: 'core'}]->(s);
MATCH (r:Role {id: 'role-ux-researcher'}), (s:DesignSkill {id: 'ds-usability-testing'}) CREATE (r)-[:REQUIRES {importance: 'core'}]->(s);
MATCH (r:Role {id: 'role-ux-researcher'}), (s:DesignSkill {id: 'ds-affinity-diag'}) CREATE (r)-[:REQUIRES {importance: 'secondary'}]->(s);
MATCH (r:Role {id: 'role-ux-researcher'}), (s:DesignSkill {id: 'ds-persona-creation'}) CREATE (r)-[:REQUIRES {importance: 'secondary'}]->(s);
MATCH (r:Role {id: 'role-ux-researcher'}), (s:DesignSkill {id: 'ds-journey-mapping'}) CREATE (r)-[:REQUIRES {importance: 'secondary'}]->(s);
MATCH (r:Role {id: 'role-ux-researcher'}), (s:DesignSkill {id: 'ds-stakeholder-pres'}) CREATE (r)-[:REQUIRES {importance: 'secondary'}]->(s);
MATCH (r:Role {id: 'role-ux-researcher'}), (s:DesignSkill {id: 'ds-survey-design'}) CREATE (r)-[:REQUIRES {importance: 'secondary'}]->(s);
MATCH (r:Role {id: 'role-ux-designer'}), (s:DesignSkill {id: 'ds-wireframing'}) CREATE (r)-[:REQUIRES {importance: 'core'}]->(s);
MATCH (r:Role {id: 'role-ux-designer'}), (s:DesignSkill {id: 'ds-prototyping'}) CREATE (r)-[:REQUIRES {importance: 'core'}]->(s);
MATCH (r:Role {id: 'role-ux-designer'}), (s:DesignSkill {id: 'ds-interaction-design'}) CREATE (r)-[:REQUIRES {importance: 'core'}]->(s);
MATCH (r:Role {id: 'role-ux-designer'}), (s:DesignSkill {id: 'ds-user-flows'}) CREATE (r)-[:REQUIRES {importance: 'core'}]->(s);
MATCH (r:Role {id: 'role-ux-designer'}), (s:DesignSkill {id: 'ds-usability-testing'}) CREATE (r)-[:REQUIRES {importance: 'secondary'}]->(s);
MATCH (r:Role {id: 'role-ux-designer'}), (s:DesignSkill {id: 'ds-design-systems'}) CREATE (r)-[:REQUIRES {importance: 'secondary'}]->(s);
MATCH (r:Role {id: 'role-visual-designer'}), (s:DesignSkill {id: 'ds-visual-design'}) CREATE (r)-[:REQUIRES {importance: 'core'}]->(s);
MATCH (r:Role {id: 'role-visual-designer'}), (s:DesignSkill {id: 'ds-visual-hierarchy'}) CREATE (r)-[:REQUIRES {importance: 'core'}]->(s);
MATCH (r:Role {id: 'role-visual-designer'}), (s:DesignSkill {id: 'ds-typography'}) CREATE (r)-[:REQUIRES {importance: 'core'}]->(s);
MATCH (r:Role {id: 'role-visual-designer'}), (s:DesignSkill {id: 'ds-color-theory'}) CREATE (r)-[:REQUIRES {importance: 'core'}]->(s);
MATCH (r:Role {id: 'role-visual-designer'}), (s:DesignSkill {id: 'ds-brand-design'}) CREATE (r)-[:REQUIRES {importance: 'secondary'}]->(s);
MATCH (r:Role {id: 'role-content-designer'}), (s:DesignSkill {id: 'ds-content-strategy'}) CREATE (r)-[:REQUIRES {importance: 'core'}]->(s);
MATCH (r:Role {id: 'role-content-designer'}), (s:DesignSkill {id: 'ds-ux-writing'}) CREATE (r)-[:REQUIRES {importance: 'core'}]->(s);
MATCH (r:Role {id: 'role-content-designer'}), (s:DesignSkill {id: 'ds-microcopy'}) CREATE (r)-[:REQUIRES {importance: 'core'}]->(s);
MATCH (r:Role {id: 'role-ia'}), (s:DesignSkill {id: 'ds-info-arch'}) CREATE (r)-[:REQUIRES {importance: 'core'}]->(s);
MATCH (r:Role {id: 'role-ia'}), (s:DesignSkill {id: 'ds-card-sorting'}) CREATE (r)-[:REQUIRES {importance: 'secondary'}]->(s);
MATCH (r:Role {id: 'role-ia'}), (s:DesignSkill {id: 'ds-user-flows'}) CREATE (r)-[:REQUIRES {importance: 'core'}]->(s);
MATCH (r:Role {id: 'role-ia'}), (s:DesignSkill {id: 'ds-systems-thinking'}) CREATE (r)-[:REQUIRES {importance: 'secondary'}]->(s);
MATCH (r:Role {id: 'role-product-designer'}), (s:DesignSkill {id: 'ds-design-thinking'}) CREATE (r)-[:REQUIRES {importance: 'core'}]->(s);
MATCH (r:Role {id: 'role-product-designer'}), (s:DesignSkill {id: 'ds-prototyping'}) CREATE (r)-[:REQUIRES {importance: 'core'}]->(s);
MATCH (r:Role {id: 'role-product-designer'}), (s:DesignSkill {id: 'ds-user-flows'}) CREATE (r)-[:REQUIRES {importance: 'core'}]->(s);
MATCH (r:Role {id: 'role-product-designer'}), (s:DesignSkill {id: 'ds-visual-design'}) CREATE (r)-[:REQUIRES {importance: 'secondary'}]->(s);
MATCH (r:Role {id: 'role-product-designer'}), (s:DesignSkill {id: 'ds-qual-analysis'}) CREATE (r)-[:REQUIRES {importance: 'secondary'}]->(s);
MATCH (r:Role {id: 'role-product-designer'}), (s:DesignSkill {id: 'ds-cross-functional'}) CREATE (r)-[:REQUIRES {importance: 'secondary'}]->(s);
MATCH (r:Role {id: 'role-ai-design-researcher'}), (s:DesignSkill {id: 'ds-qual-analysis'}) CREATE (r)-[:REQUIRES {importance: 'core'}]->(s);
MATCH (r:Role {id: 'role-ai-design-researcher'}), (s:DesignSkill {id: 'ds-usability-testing'}) CREATE (r)-[:REQUIRES {importance: 'core'}]->(s);
MATCH (r:Role {id: 'role-ai-design-researcher'}), (a:AICapability {id: 'ai-prompt-eval'}) CREATE (r)-[:REQUIRES {importance: 'core'}]->(a);
MATCH (r:Role {id: 'role-ai-design-researcher'}), (a:AICapability {id: 'ai-output-assessment'}) CREATE (r)-[:REQUIRES {importance: 'core'}]->(a);
MATCH (r:Role {id: 'role-ai-design-researcher'}), (a:AICapability {id: 'ai-synthetic-users'}) CREATE (r)-[:REQUIRES {importance: 'secondary'}]->(a);
MATCH (r:Role {id: 'role-ai-design-researcher'}), (a:AICapability {id: 'ai-tool-proficiency'}) CREATE (r)-[:REQUIRES {importance: 'core'}]->(a);
MATCH (r:Role {id: 'role-ai-design-researcher'}), (a:AICapability {id: 'ai-ml-literacy'}) CREATE (r)-[:REQUIRES {importance: 'secondary'}]->(a);
MATCH (r:Role {id: 'role-ai-design-researcher'}), (a:AICapability {id: 'ai-ethics-eval'}) CREATE (r)-[:REQUIRES {importance: 'secondary'}]->(a);
MATCH (r:Role {id: 'role-ai-design-researcher'}), (a:AICapability {id: 'ai-testing-ai'}) CREATE (r)-[:REQUIRES {importance: 'secondary'}]->(a);
MATCH (r:Role {id: 'role-ai-ux-lead'}), (s:DesignSkill {id: 'ds-design-thinking'}) CREATE (r)-[:REQUIRES {importance: 'core'}]->(s);
MATCH (r:Role {id: 'role-ai-ux-lead'}), (s:DesignSkill {id: 'ds-stakeholder-pres'}) CREATE (r)-[:REQUIRES {importance: 'core'}]->(s);
MATCH (r:Role {id: 'role-ai-ux-lead'}), (a:AICapability {id: 'ai-ux-ai-patterns'}) CREATE (r)-[:REQUIRES {importance: 'core'}]->(a);
MATCH (r:Role {id: 'role-ai-ux-lead'}), (a:AICapability {id: 'ai-human-ai-collab'}) CREATE (r)-[:REQUIRES {importance: 'core'}]->(a);
MATCH (r:Role {id: 'role-ai-ux-lead'}), (a:AICapability {id: 'ai-ml-literacy'}) CREATE (r)-[:REQUIRES {importance: 'secondary'}]->(a);
MATCH (r:Role {id: 'role-ai-ux-lead'}), (a:AICapability {id: 'ai-prompt-eng'}) CREATE (r)-[:REQUIRES {importance: 'secondary'}]->(a);
MATCH (r:Role {id: 'role-ai-ux-lead'}), (a:AICapability {id: 'ai-tool-proficiency'}) CREATE (r)-[:REQUIRES {importance: 'core'}]->(a);
MATCH (r:Role {id: 'role-ai-ux-lead'}), (a:AICapability {id: 'ai-workflow-design'}) CREATE (r)-[:REQUIRES {importance: 'secondary'}]->(a);
MATCH (r:Role {id: 'role-conv-ui-designer'}), (a:AICapability {id: 'ai-conversational-ai'}) CREATE (r)-[:REQUIRES {importance: 'core'}]->(a);
MATCH (r:Role {id: 'role-conv-ui-designer'}), (a:AICapability {id: 'ai-prompt-eng'}) CREATE (r)-[:REQUIRES {importance: 'core'}]->(a);
MATCH (r:Role {id: 'role-conv-ui-designer'}), (a:AICapability {id: 'ai-persona-agent'}) CREATE (r)-[:REQUIRES {importance: 'core'}]->(a);
MATCH (r:Role {id: 'role-conv-ui-designer'}), (a:AICapability {id: 'ai-voice-ai'}) CREATE (r)-[:REQUIRES {importance: 'secondary'}]->(a);
MATCH (r:Role {id: 'role-conv-ui-designer'}), (s:DesignSkill {id: 'ds-conversational-design'}) CREATE (r)-[:REQUIRES {importance: 'core'}]->(s);
MATCH (r:Role {id: 'role-conv-ui-designer'}), (s:DesignSkill {id: 'ds-ux-writing'}) CREATE (r)-[:REQUIRES {importance: 'secondary'}]->(s);
MATCH (r:Role {id: 'role-conv-ui-designer'}), (a:AICapability {id: 'ai-ml-literacy'}) CREATE (r)-[:REQUIRES {importance: 'secondary'}]->(a);
MATCH (r:Role {id: 'role-ai-content-strategist'}), (s:DesignSkill {id: 'ds-content-strategy'}) CREATE (r)-[:REQUIRES {importance: 'core'}]->(s);
MATCH (r:Role {id: 'role-ai-content-strategist'}), (a:AICapability {id: 'ai-prompt-eng'}) CREATE (r)-[:REQUIRES {importance: 'core'}]->(a);
MATCH (r:Role {id: 'role-ai-content-strategist'}), (a:AICapability {id: 'ai-content-gen'}) CREATE (r)-[:REQUIRES {importance: 'core'}]->(a);
MATCH (r:Role {id: 'role-ai-content-strategist'}), (a:AICapability {id: 'ai-prompt-chaining'}) CREATE (r)-[:REQUIRES {importance: 'secondary'}]->(a);
MATCH (r:Role {id: 'role-ai-content-strategist'}), (a:AICapability {id: 'ai-ethics-eval'}) CREATE (r)-[:REQUIRES {importance: 'secondary'}]->(a);
MATCH (r:Role {id: 'role-ai-content-strategist'}), (a:AICapability {id: 'ai-personalization'}) CREATE (r)-[:REQUIRES {importance: 'secondary'}]->(a);
MATCH (r:Role {id: 'role-ai-product-designer'}), (s:DesignSkill {id: 'ds-design-thinking'}) CREATE (r)-[:REQUIRES {importance: 'core'}]->(s);
MATCH (r:Role {id: 'role-ai-product-designer'}), (s:DesignSkill {id: 'ds-prototyping'}) CREATE (r)-[:REQUIRES {importance: 'core'}]->(s);
MATCH (r:Role {id: 'role-ai-product-designer'}), (a:AICapability {id: 'ai-ux-ai-patterns'}) CREATE (r)-[:REQUIRES {importance: 'core'}]->(a);
MATCH (r:Role {id: 'role-ai-product-designer'}), (a:AICapability {id: 'ai-prompt-eng'}) CREATE (r)-[:REQUIRES {importance: 'core'}]->(a);
MATCH (r:Role {id: 'role-ai-product-designer'}), (a:AICapability {id: 'ai-ml-literacy'}) CREATE (r)-[:REQUIRES {importance: 'secondary'}]->(a);
MATCH (r:Role {id: 'role-ai-product-designer'}), (a:AICapability {id: 'ai-gen-ui'}) CREATE (r)-[:REQUIRES {importance: 'secondary'}]->(a);
MATCH (r:Role {id: 'role-ai-product-designer'}), (a:AICapability {id: 'ai-human-ai-collab'}) CREATE (r)-[:REQUIRES {importance: 'secondary'}]->(a);
MATCH (r:Role {id: 'role-ai-design-lead'}), (s:DesignSkill {id: 'ds-stakeholder-pres'}) CREATE (r)-[:REQUIRES {importance: 'core'}]->(s);
MATCH (r:Role {id: 'role-ai-design-lead'}), (s:DesignSkill {id: 'ds-design-thinking'}) CREATE (r)-[:REQUIRES {importance: 'core'}]->(s);
MATCH (r:Role {id: 'role-ai-design-lead'}), (s:DesignSkill {id: 'ds-cross-functional'}) CREATE (r)-[:REQUIRES {importance: 'core'}]->(s);
MATCH (r:Role {id: 'role-ai-design-lead'}), (a:AICapability {id: 'ai-human-ai-collab'}) CREATE (r)-[:REQUIRES {importance: 'core'}]->(a);
MATCH (r:Role {id: 'role-ai-design-lead'}), (a:AICapability {id: 'ai-workflow-design'}) CREATE (r)-[:REQUIRES {importance: 'core'}]->(a);
MATCH (r:Role {id: 'role-ai-design-lead'}), (a:AICapability {id: 'ai-ux-ai-patterns'}) CREATE (r)-[:REQUIRES {importance: 'core'}]->(a);
MATCH (r:Role {id: 'role-ai-design-lead'}), (a:AICapability {id: 'ai-ml-literacy'}) CREATE (r)-[:REQUIRES {importance: 'secondary'}]->(a);
MATCH (r:Role {id: 'role-ai-design-lead'}), (a:AICapability {id: 'ai-model-selection'}) CREATE (r)-[:REQUIRES {importance: 'secondary'}]->(a);
MATCH (r:Role {id: 'role-ai-design-lead'}), (a:AICapability {id: 'ai-tool-proficiency'}) CREATE (r)-[:REQUIRES {importance: 'core'}]->(a);
MATCH (r:Role {id: 'role-ai-design-engineer'}), (s:DesignSkill {id: 'ds-front-end-basics'}) CREATE (r)-[:REQUIRES {importance: 'core'}]->(s);
MATCH (r:Role {id: 'role-ai-design-engineer'}), (s:DesignSkill {id: 'ds-prototyping'}) CREATE (r)-[:REQUIRES {importance: 'core'}]->(s);
MATCH (r:Role {id: 'role-ai-design-engineer'}), (a:AICapability {id: 'ai-gen-ui'}) CREATE (r)-[:REQUIRES {importance: 'core'}]->(a);
MATCH (r:Role {id: 'role-ai-design-engineer'}), (a:AICapability {id: 'ai-prompt-eng'}) CREATE (r)-[:REQUIRES {importance: 'core'}]->(a);
MATCH (r:Role {id: 'role-ai-design-engineer'}), (a:AICapability {id: 'ai-ml-literacy'}) CREATE (r)-[:REQUIRES {importance: 'secondary'}]->(a);
MATCH (r:Role {id: 'role-ai-design-engineer'}), (a:AICapability {id: 'ai-automation'}) CREATE (r)-[:REQUIRES {importance: 'secondary'}]->(a);
MATCH (r:Role {id: 'role-ai-ethics-designer'}), (s:DesignSkill {id: 'ds-inclusive-design'}) CREATE (r)-[:REQUIRES {importance: 'core'}]->(s);
MATCH (r:Role {id: 'role-ai-ethics-designer'}), (s:DesignSkill {id: 'ds-accessibility'}) CREATE (r)-[:REQUIRES {importance: 'core'}]->(s);
MATCH (r:Role {id: 'role-ai-ethics-designer'}), (a:AICapability {id: 'ai-ethics-eval'}) CREATE (r)-[:REQUIRES {importance: 'core'}]->(a);
MATCH (r:Role {id: 'role-ai-ethics-designer'}), (a:AICapability {id: 'ai-output-assessment'}) CREATE (r)-[:REQUIRES {importance: 'core'}]->(a);
MATCH (r:Role {id: 'role-ai-ethics-designer'}), (a:AICapability {id: 'ai-ml-literacy'}) CREATE (r)-[:REQUIRES {importance: 'secondary'}]->(a);
MATCH (r:Role {id: 'role-ai-ethics-designer'}), (a:AICapability {id: 'ai-accessibility-ai'}) CREATE (r)-[:REQUIRES {importance: 'secondary'}]->(a);
MATCH (r1:Role {id: 'role-ux-researcher'}), (r2:Role {id: 'role-ai-design-researcher'}) CREATE (r1)-[:LEADS_TO {difficulty: 'moderate', typical_months: 3}]->(r2);
MATCH (r1:Role {id: 'role-ux-researcher'}), (r2:Role {id: 'role-ai-ux-lead'}) CREATE (r1)-[:LEADS_TO {difficulty: 'challenging', typical_months: 6}]->(r2);
MATCH (r1:Role {id: 'role-ux-designer'}), (r2:Role {id: 'role-ai-product-designer'}) CREATE (r1)-[:LEADS_TO {difficulty: 'moderate', typical_months: 4}]->(r2);
MATCH (r1:Role {id: 'role-ux-designer'}), (r2:Role {id: 'role-ai-ux-lead'}) CREATE (r1)-[:LEADS_TO {difficulty: 'challenging', typical_months: 6}]->(r2);
MATCH (r1:Role {id: 'role-ux-designer'}), (r2:Role {id: 'role-conv-ui-designer'}) CREATE (r1)-[:LEADS_TO {difficulty: 'moderate', typical_months: 4}]->(r2);
MATCH (r1:Role {id: 'role-visual-designer'}), (r2:Role {id: 'role-ai-product-designer'}) CREATE (r1)-[:LEADS_TO {difficulty: 'challenging', typical_months: 6}]->(r2);
MATCH (r1:Role {id: 'role-visual-designer'}), (r2:Role {id: 'role-ai-design-engineer'}) CREATE (r1)-[:LEADS_TO {difficulty: 'challenging', typical_months: 8}]->(r2);
MATCH (r1:Role {id: 'role-content-designer'}), (r2:Role {id: 'role-ai-content-strategist'}) CREATE (r1)-[:LEADS_TO {difficulty: 'moderate', typical_months: 3}]->(r2);
MATCH (r1:Role {id: 'role-content-designer'}), (r2:Role {id: 'role-conv-ui-designer'}) CREATE (r1)-[:LEADS_TO {difficulty: 'moderate', typical_months: 4}]->(r2);
MATCH (r1:Role {id: 'role-ia'}), (r2:Role {id: 'role-ai-product-designer'}) CREATE (r1)-[:LEADS_TO {difficulty: 'moderate', typical_months: 4}]->(r2);
MATCH (r1:Role {id: 'role-ia'}), (r2:Role {id: 'role-ai-design-engineer'}) CREATE (r1)-[:LEADS_TO {difficulty: 'challenging', typical_months: 6}]->(r2);
MATCH (r1:Role {id: 'role-product-designer'}), (r2:Role {id: 'role-ai-product-designer'}) CREATE (r1)-[:LEADS_TO {difficulty: 'easy', typical_months: 2}]->(r2);
MATCH (r1:Role {id: 'role-product-designer'}), (r2:Role {id: 'role-ai-design-lead'}) CREATE (r1)-[:LEADS_TO {difficulty: 'moderate', typical_months: 4}]->(r2);
MATCH (r1:Role {id: 'role-graphic-designer'}), (r2:Role {id: 'role-ai-product-designer'}) CREATE (r1)-[:LEADS_TO {difficulty: 'challenging', typical_months: 6}]->(r2);
MATCH (r1:Role {id: 'role-ai-product-designer'}), (r2:Role {id: 'role-ai-design-lead'}) CREATE (r1)-[:LEADS_TO {difficulty: 'moderate', typical_months: 6}]->(r2);
MATCH (r1:Role {id: 'role-ai-design-researcher'}), (r2:Role {id: 'role-ai-ux-lead'}) CREATE (r1)-[:LEADS_TO {difficulty: 'moderate', typical_months: 4}]->(r2);
MATCH (c:Course {id: 'course-ixdf-ai-design'}), (a:AICapability {id: 'ai-ml-literacy'}) CREATE (c)-[:TEACHES]->(a);
MATCH (c:Course {id: 'course-ixdf-ai-design'}), (a:AICapability {id: 'ai-ux-ai-patterns'}) CREATE (c)-[:TEACHES]->(a);
MATCH (c:Course {id: 'course-coursera-prompt'}), (a:AICapability {id: 'ai-prompt-eng'}) CREATE (c)-[:TEACHES]->(a);
MATCH (c:Course {id: 'course-coursera-prompt'}), (a:AICapability {id: 'ai-prompt-chaining'}) CREATE (c)-[:TEACHES]->(a);
MATCH (c:Course {id: 'course-nngroup-ai-ux'}), (a:AICapability {id: 'ai-ux-ai-patterns'}) CREATE (c)-[:TEACHES]->(a);
MATCH (c:Course {id: 'course-nngroup-ai-ux'}), (a:AICapability {id: 'ai-human-ai-collab'}) CREATE (c)-[:TEACHES]->(a);
MATCH (c:Course {id: 'course-figma-ai-workshop'}), (a:AICapability {id: 'ai-tool-proficiency'}) CREATE (c)-[:TEACHES]->(a);
MATCH (c:Course {id: 'course-figma-ai-workshop'}), (a:AICapability {id: 'ai-gen-ui'}) CREATE (c)-[:TEACHES]->(a);
MATCH (c:Course {id: 'course-ml-nontech'}), (a:AICapability {id: 'ai-ml-literacy'}) CREATE (c)-[:TEACHES]->(a);
MATCH (c:Course {id: 'course-ai-ethics'}), (a:AICapability {id: 'ai-ethics-eval'}) CREATE (c)-[:TEACHES]->(a);
MATCH (c:Course {id: 'course-conv-design'}), (a:AICapability {id: 'ai-conversational-ai'}) CREATE (c)-[:TEACHES]->(a);
MATCH (c:Course {id: 'course-conv-design'}), (a:AICapability {id: 'ai-persona-agent'}) CREATE (c)-[:TEACHES]->(a);
MATCH (c:Course {id: 'course-midjourney-mastery'}), (a:AICapability {id: 'ai-image-prompting'}) CREATE (c)-[:TEACHES]->(a);
MATCH (c:Course {id: 'course-midjourney-mastery'}), (a:AICapability {id: 'ai-tool-proficiency'}) CREATE (c)-[:TEACHES]->(a);
MATCH (c:Course {id: 'course-ai-research-methods'}), (a:AICapability {id: 'ai-synthetic-users'}) CREATE (c)-[:TEACHES]->(a);
MATCH (c:Course {id: 'course-ai-research-methods'}), (a:AICapability {id: 'ai-testing-ai'}) CREATE (c)-[:TEACHES]->(a);
MATCH (c:Course {id: 'course-design-systems-ai'}), (a:AICapability {id: 'ai-gen-ui'}) CREATE (c)-[:TEACHES]->(a);
MATCH (c:Course {id: 'course-design-systems-ai'}), (a:AICapability {id: 'ai-automation'}) CREATE (c)-[:TEACHES]->(a);
MATCH (c:Course {id: 'course-data-viz-ai'}), (a:AICapability {id: 'ai-data-viz-ai'}) CREATE (c)-[:TEACHES]->(a);
MATCH (c:Course {id: 'course-genui-basics'}), (a:AICapability {id: 'ai-gen-ui'}) CREATE (c)-[:TEACHES]->(a);
MATCH (c:Course {id: 'course-voice-ai-design'}), (a:AICapability {id: 'ai-voice-ai'}) CREATE (c)-[:TEACHES]->(a);
MATCH (c:Course {id: 'course-ai-content-strategy'}), (a:AICapability {id: 'ai-content-gen'}) CREATE (c)-[:TEACHES]->(a);
MATCH (c:Course {id: 'course-ai-content-strategy'}), (a:AICapability {id: 'ai-prompt-eng'}) CREATE (c)-[:TEACHES]->(a);
MATCH (c:Course {id: 'course-rag-basics'}), (a:AICapability {id: 'ai-rag'}) CREATE (c)-[:TEACHES]->(a);
MATCH (c:Course {id: 'course-human-ai-collab'}), (a:AICapability {id: 'ai-human-ai-collab'}) CREATE (c)-[:TEACHES]->(a);
MATCH (c:Course {id: 'course-ai-persona-design'}), (a:AICapability {id: 'ai-persona-agent'}) CREATE (c)-[:TEACHES]->(a);
MATCH (c:Course {id: 'course-multimodal-ai'}), (a:AICapability {id: 'ai-multimodal'}) CREATE (c)-[:TEACHES]->(a);
MATCH (c:Course {id: 'course-ai-accessibility'}), (a:AICapability {id: 'ai-accessibility-ai'}) CREATE (c)-[:TEACHES]->(a);
MATCH (c:Course {id: 'course-prompt-chaining'}), (a:AICapability {id: 'ai-prompt-chaining'}) CREATE (c)-[:TEACHES]->(a);
MATCH (t:Tool {id: 'tool-figma-ai'}), (a:AICapability {id: 'ai-gen-ui'}) CREATE (t)-[:DEVELOPS]->(a);
MATCH (t:Tool {id: 'tool-figma-ai'}), (a:AICapability {id: 'ai-tool-proficiency'}) CREATE (t)-[:DEVELOPS]->(a);
MATCH (t:Tool {id: 'tool-midjourney'}), (a:AICapability {id: 'ai-image-prompting'}) CREATE (t)-[:DEVELOPS]->(a);
MATCH (t:Tool {id: 'tool-midjourney'}), (a:AICapability {id: 'ai-prompt-eng'}) CREATE (t)-[:DEVELOPS]->(a);
MATCH (t:Tool {id: 'tool-dalle'}), (a:AICapability {id: 'ai-image-prompting'}) CREATE (t)-[:DEVELOPS]->(a);
MATCH (t:Tool {id: 'tool-chatgpt'}), (a:AICapability {id: 'ai-prompt-eng'}) CREATE (t)-[:DEVELOPS]->(a);
MATCH (t:Tool {id: 'tool-chatgpt'}), (a:AICapability {id: 'ai-content-gen'}) CREATE (t)-[:DEVELOPS]->(a);
MATCH (t:Tool {id: 'tool-claude'}), (a:AICapability {id: 'ai-prompt-eng'}) CREATE (t)-[:DEVELOPS]->(a);
MATCH (t:Tool {id: 'tool-claude'}), (a:AICapability {id: 'ai-prompt-chaining'}) CREATE (t)-[:DEVELOPS]->(a);
MATCH (t:Tool {id: 'tool-adobe-firefly'}), (a:AICapability {id: 'ai-image-prompting'}) CREATE (t)-[:DEVELOPS]->(a);
MATCH (t:Tool {id: 'tool-adobe-firefly'}), (a:AICapability {id: 'ai-tool-proficiency'}) CREATE (t)-[:DEVELOPS]->(a);
MATCH (t:Tool {id: 'tool-usertesting-ai'}), (a:AICapability {id: 'ai-synthetic-users'}) CREATE (t)-[:DEVELOPS]->(a);
MATCH (t:Tool {id: 'tool-usertesting-ai'}), (a:AICapability {id: 'ai-testing-ai'}) CREATE (t)-[:DEVELOPS]->(a);
MATCH (t:Tool {id: 'tool-maze-ai'}), (a:AICapability {id: 'ai-testing-ai'}) CREATE (t)-[:DEVELOPS]->(a);
MATCH (t:Tool {id: 'tool-stable-diffusion'}), (a:AICapability {id: 'ai-image-prompting'}) CREATE (t)-[:DEVELOPS]->(a);
MATCH (t:Tool {id: 'tool-copilot'}), (a:AICapability {id: 'ai-automation'}) CREATE (t)-[:DEVELOPS]->(a);
MATCH (t:Tool {id: 'tool-v0'}), (a:AICapability {id: 'ai-gen-ui'}) CREATE (t)-[:DEVELOPS]->(a);
MATCH (t:Tool {id: 'tool-cursor'}), (a:AICapability {id: 'ai-automation'}) CREATE (t)-[:DEVELOPS]->(a);
MATCH (t:Tool {id: 'tool-framer-ai'}), (a:AICapability {id: 'ai-gen-ui'}) CREATE (t)-[:DEVELOPS]->(a);
MATCH (t:Tool {id: 'tool-relume'}), (a:AICapability {id: 'ai-gen-ui'}) CREATE (t)-[:DEVELOPS]->(a);
MATCH (t:Tool {id: 'tool-galileo-ai'}), (a:AICapability {id: 'ai-gen-ui'}) CREATE (t)-[:DEVELOPS]->(a);
