CREATE CONSTRAINT IF NOT EXISTS FOR (s:DesignSkill) REQUIRE s.id IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS FOR (a:AICapability) REQUIRE a.id IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS FOR (r:Role) REQUIRE r.id IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS FOR (t:Tool) REQUIRE t.id IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS FOR (c:Course) REQUIRE c.id IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS FOR (cert:Certification) REQUIRE cert.id IS UNIQUE;
CREATE INDEX IF NOT EXISTS FOR (s:DesignSkill) ON (s.name);
CREATE INDEX IF NOT EXISTS FOR (a:AICapability) ON (a.name);
CREATE INDEX IF NOT EXISTS FOR (r:Role) ON (r.name);
